tests/Suite/Engine/HashTest.php
tests/files/algoSplits.json

Add tests that populate a redis cache with splits,
retrieve those splits, verify the algo fields returns accurate values
and verifies that the hash factory returns the appropriate class function depending on the algo field.

Test algo field

---

src/SplitIO/Component/Initialization/LoggerTrait.php
src/SplitIO/Component/Log/Handler/Void.php
src/SplitIO/Component/Log/Logger.php

Rename Void log handler to avoid conflicts with PHP7.1 new Void type

Quick fix for php7.1

---

src/SplitIO/Engine.php
src/SplitIO/Engine/Splitter.php
src/SplitIO/Grammar/Condition.php
src/SplitIO/Grammar/Condition/ConditionTypeEnum.php
src/SplitIO/Grammar/Split.php
src/SplitIO/Sdk/Impressions/ImpressionLabel.php
tests/Suite/Engine/SplitterTest.php

add "Trafic Allocation" feature

---

phpunit.xml.dist
src/SplitIO/Grammar/Condition/Matcher.php
src/SplitIO/Grammar/Condition/Matcher/AbstractMatcher.php
src/SplitIO/Grammar/Condition/Matcher/ContainsAllOfSet.php
src/SplitIO/Grammar/Condition/Matcher/ContainsAnyOfSet.php
src/SplitIO/Grammar/Condition/Matcher/ContainsString.php
src/SplitIO/Grammar/Condition/Matcher/DataType/Set.php
src/SplitIO/Grammar/Condition/Matcher/EndsWith.php
src/SplitIO/Grammar/Condition/Matcher/EqualToSet.php
src/SplitIO/Grammar/Condition/Matcher/PartOfSet.php
src/SplitIO/Grammar/Condition/Matcher/StartsWith.php
tests/Suite/Matchers/MatchersTest.php
tests/Suite/Matchers/SetTest.php

String & Set matchers

---

phpunit.xml.dist
src/SplitIO/Component/Cache/BlockUntilReadyCache.php
src/SplitIO/Component/Cache/ImpressionCache.php
src/SplitIO/Component/Cache/KeyFactory.php
src/SplitIO/Component/Cache/MetricsCache.php
src/SplitIO/Component/Cache/SegmentCache.php
src/SplitIO/Component/Cache/Storage/Adapter/PRedis.php
src/SplitIO/Sdk.php
src/SplitIO/functions.php
tests/Suite/Component/KeysStaticMethodsTest.php

Update redis keys structure

---

src/SplitIO/Grammar/Split.php

Itearate through all conditions and partitions and generate and array with the results of all

[HOTFIX] - Return treatments from all conditions

---

phpunit.xml.dist
src/SplitIO/Sdk/Client.php
src/SplitIO/Sdk/Events/EventDTO.php
src/SplitIO/Sdk/Manager/SplitManager.php
src/SplitIO/Sdk/Validator/InputValidator.php
src/SplitIO/functions.php
tests/Suite/InputValidation/GetTreatmentsValidationTest.php
tests/Suite/InputValidation/ManagerValidationTest.php
tests/Suite/InputValidation/TrackValidationTest.php
tests/Suite/Redis/PRedisReadOnlyMock.php

[SDKS-30: PHP Input Validation](https://splitio.atlassian.net/browse/SDKS-30)
[SDKS-182:Add input validation logic for track, getTreatment and manager](https://splitio.atlassian.net/browse/SDKS-182)
[SDKS-183: Add Unit Tests](https://splitio.atlassian.net/browse/SDKS-183)
- Added check statements for `getTreatment`, `track` and `split` methods regarding the parameters received.
- Updated `toString` in `functions.php` in order to inform errors when parameter type is not the expected one.
- Added unit test . for `getTreatment`, `track` and `split` methods.

[SDKS-30] PHP Input Validation

---

CHANGES.txt
NEWS.txt
src/SplitIO/Version.php
src/SplitIO/functions.php
tests/Suite/Sdk/ImpressionWrapperTest.php

[SDKS-238: Add unknown machine IP when variable is not present](https://splitio.atlassian.net/browse/SDKS-238)
- Fixed issue when ipAddress or SERVER_ADDR is empty.

[SDKS-238]: Add unknown machine IP when variable is not present

---

.github/pull_request_template.md
CHANGES.txt
NEWS.txt
src/SplitIO/Sdk/Client.php
src/SplitIO/Sdk/Validator/InputValidator.php
src/SplitIO/Version.php
tests/Suite/InputValidation/GetTreatmentValidationTest.php
tests/Suite/InputValidation/GetTreatmentsValidationTest.php
tests/Suite/InputValidation/ManagerValidationTest.php
tests/Suite/InputValidation/TrackValidationTest.php
tests/Suite/Sdk/SdkClientTest.php

[SDKS-129: Get Treatments](https://splitio.atlassian.net/browse/SDKS-129)
- Added `getTreatments` method.

[SDKS-129]: Get Treatments

---

CHANGES.txt
NEWS.txt
src/SplitIO/Exception/KeyException.php
src/SplitIO/Sdk/Client.php
src/SplitIO/Sdk/Key.php
src/SplitIO/Sdk/Manager/SplitManager.php
src/SplitIO/Sdk/Validator/InputValidator.php
src/SplitIO/Version.php
src/SplitIO/functions.php
tests/Suite/InputValidation/GetTreatmentValidationTest.php
tests/Suite/InputValidation/GetTreatmentsValidationTest.php
tests/Suite/InputValidation/ManagerValidationTest.php
tests/Suite/InputValidation/TrackValidationTest.php

* [SDK-412: PHP input validation](https://splitio.atlassian.net/browse/SDKS-412)
* Updated input validation for PHP

[SDK-412]: PHP input validation

---

CHANGES.txt
NEWS.txt
src/SplitIO/Version.php

new release version

---

CHANGES.txt
NEWS.txt
src/SplitIO/Version.php

* NO-TICKET
* Made the new version as a breaking change.

[NO-TICKET]: Move to breaking change

---

CHANGES.txt
NEWS.txt

* [PHP: {TITLE}](https://splitio.atlassian.net/browse/SDKS-{NUMBER})
* Bullet 1
* Bullet 2
* Bullet 1
* Bullet 2

updated changelog

---

CHANGES.txt
NEWS.txt
src/SplitIO/Metrics.php
src/SplitIO/Sdk/Client.php
tests/Suite/Sdk/SdkClientTest.php
tests/Suite/Sdk/files/splitChanges.json
tests/files/splitChanges.json

* [SDKS-576: Add new treatmentWithConfig method](https://splitio.atlassian.net/browse/SDKS-576)
* Added `getTreatmentWithConfig` method.
* Updated tests.

[SDKS-576]: Add new treatmentWithConfig method

---

Detailed-README.md
src/SplitIO/Sdk/Manager/SplitManager.php
src/SplitIO/Sdk/Manager/SplitView.php
tests/Suite/Sdk/SdkClientTest.php
tests/Suite/Sdk/files/splitChanges.json

* [SDKS-576: Update SplitView for Manager](https://splitio.atlassian.net/browse/SDKS-576)
* Added logic to return configuration in manager calls.
* Updated tests

[SDKS-576]: Update SplitView for Manager

---

composer.json

* Updating the symfony-yaml version to 4.*

Updating symfony-yaml to 4.*

---

CHANGES.txt
NEWS.txt
src/SplitIO/Component/Utils/functions.php
src/SplitIO/Sdk/Client.php
src/SplitIO/Sdk/Events/EventDTO.php
src/SplitIO/Sdk/Validator/InputValidator.php
src/SplitIO/Version.php
tests/Suite/InputValidation/TrackValidationTest.php
tests/Suite/Redis/CacheInterfacesTest.php

* [SDKS-706: Add track properties](https://splitio.atlassian.net/browse/SDKS-706)
* Added new method into InputValidator to validate properties.
* Added new parameter to track method for properties.
* Added new property in EventDTO for properties.
* Added new tests for properties.

[SDKS-706]: Add track properties

---

src/SplitIO/Component/Cache/MetricsCache.php
src/SplitIO/Component/Cache/SegmentCache.php
src/SplitIO/Component/Cache/SplitCache.php
src/SplitIO/Grammar/Condition/Matcher/Dependency.php
src/SplitIO/Sdk/Client.php
src/SplitIO/Sdk/Manager/SplitManager.php
tests/Suite/Component/KeysStaticMethodsTest.php
tests/Suite/DynamicConfigurations/SplitTest.php
tests/Suite/Engine/HashTest.php
tests/Suite/Matchers/MatchersTest.php

- Remove raw accesses to redis (in favor of SplitCache / MetricsCache / etc).
- Fix manager
- Fix getTreatments impressions

Fix getTreatments impressions, remove raw accesses to cache

---

.gitignore
.travis.yml
composer.json
sonar-scanner.sh

Send a report to SonarQube for every short lived branch, merges to develop or master, and pull requests.
The report will be sent only in the PHP 7.2 Travis CI execution (to avoid a double report).
Check TravisCI logs for this branch/PR.
A full report will appear when master is analyzed.

SonarQube scanner

---

.github/workflows/update-license-year.yml
LICENSE

added GHA for updating license year

---

src/SplitIO/Component/Cache/Pool.php
src/SplitIO/Component/Cache/SplitCache.php
src/SplitIO/Component/Cache/SplitCacheInterface.php
src/SplitIO/Component/Cache/Storage/Adapter/CacheStorageAdapterInterface.php
src/SplitIO/Component/Cache/Storage/Adapter/PRedis.php
src/SplitIO/Component/Cache/Storage/Adapter/SafeRedisWrapper.php
tests/Suite/Attributes/files/splitChanges.json
tests/Suite/Redis/CacheInterfacesTest.php
tests/Suite/Redis/SafeRedisWrapperTest.php
tests/Suite/Sdk/files/splitChanges.json
tests/Suite/Sdk/files/splitReadOnly.json
tests/Suite/Sdk/files/splitil.json
tests/Utils/Utils.php
tests/files/algoSplits.json
tests/files/splitChanges.json

- Adding getNamesByFlagSets in split cache

[Flag Sets] Adding getNamesByFlagSets in split cache

---

src/SplitIO/Component/Cache/SplitCache.php
src/SplitIO/Sdk/Evaluator.php
tests/Suite/DynamicConfigurations/EvaluatorTest.php

[Flag Sets] Adding EvaluateByFlagSets

---

src/SplitIO/Grammar/Split.php
src/SplitIO/Sdk/Manager/LocalhostSplitManager.php
src/SplitIO/Sdk/Manager/SplitManager.php
src/SplitIO/Sdk/Manager/SplitView.php
tests/Suite/Sdk/SdkClientTest.php
tests/Suite/Sdk/files/splitChanges.json

- Adding DefaultTreatment in split view.
- Adding Sets in split view

[Flag Sets] Manager

---

src/SplitIO/Sdk/Manager/SplitView.php
src/SplitIO/Sdk/Validator/flagSetsValidator.php
tests/Suite/InputValidation/FlagSetsValidatorTest.php

- [Flag Sets] Input Validation

[Flag Sets] Input Validation

---

src/SplitIO/Metrics.php
src/SplitIO/Sdk/Client.php
src/SplitIO/Sdk/ClientInterface.php
src/SplitIO/Sdk/Evaluator.php
src/SplitIO/Sdk/LocalhostClient.php
src/SplitIO/Sdk/Validator/flagSetsValidator.php
tests/Suite/Sdk/SdkClientTest.php
tests/Suite/Sdk/files/splitChanges.json

-  Adding getTreatmentsByFlagSets and getTreatmentsWithConfigByFlagSets

[Flag Sets] Adding getTreatmentsByFlagSets and getTreatmentsWithConfigByFlagSets

---

src/SplitIO/Metrics.php
src/SplitIO/Sdk/Client.php
src/SplitIO/Sdk/Validator/InputValidator.php

[Flag Sets] Cleanup

---

CHANGES.txt

updated changes.txt

---

.github/workflows/ci.yml
composer.json
src/SplitIO/Component/Cache/Storage/Adapter/PRedis.php
src/SplitIO/Sdk.php
src/SplitIO/Sdk/ClientInterface.php
src/SplitIO/Sdk/Factory/SplitFactory.php
src/SplitIO/Sdk/LocalhostClient.php
tests/Suite/Adapter/RedisAdapterTest.php

forwarding predis options directly without wrapping it

---

src/SplitIO/Grammar/Condition/Matcher.php
src/SplitIO/Grammar/Condition/Matcher/BetweenSemver.php
src/SplitIO/Grammar/Condition/Matcher/EqualToSemver.php
src/SplitIO/Grammar/Condition/Matcher/InListSemver.php
tests/Suite/Matchers/MatchersTest.php
tests/Suite/Sdk/SdkClientTest.php
tests/Suite/Sdk/files/splitChanges.json
tests/Suite/Semver/ComparerTests.php

- InListSemver Matcher implementation.

InListSemver Matcher implementation.

---

src/SplitIO/Grammar/Condition/Matcher.php
src/SplitIO/Grammar/Condition/Matcher/BetweenSemver.php
src/SplitIO/Grammar/Condition/Matcher/EqualToSemver.php
src/SplitIO/Grammar/Condition/Matcher/InListSemver.php
src/SplitIO/Grammar/Condition/Matcher/LessThanOrEqualToSemver.php
tests/Suite/Matchers/MatchersTest.php
tests/Suite/Sdk/SdkClientTest.php
tests/Suite/Sdk/files/splitChanges.json
tests/Suite/Semver/ComparerTests.php

- BetweenSemver Matcher implementation.

BetweenSemver Matcher implementation.

---

src/SplitIO/Grammar/Condition/Matcher.php
src/SplitIO/Grammar/Condition/Matcher/BetweenSemver.php
src/SplitIO/Grammar/Condition/Matcher/EqualToSemver.php
src/SplitIO/Grammar/Condition/Matcher/InListSemver.php
src/SplitIO/Grammar/Condition/Matcher/LessThanOrEqualToSemver.php
tests/Suite/Matchers/MatchersTest.php
tests/Suite/Sdk/SdkClientTest.php
tests/Suite/Sdk/files/splitChanges.json
tests/Suite/Semver/ComparerTests.php

- LessThanOrEqualToSemver Matcher implementation.

LessThanOrEqualToSemver Matcher implementation.
